services:
    bookmark-manager:
        container_name: bookmark-manager
        image: ghcr.io/kai17-a/browser-bookmark-manager:latest
        # build:
        #     context: .
        #     dockerfile: Dockerfile
        environment:
            DATABASE_URL: /data/bookmark.db
        ports:
            - "3000:3000"
            - "8000:8000"
        volumes:
            - ./local-data:/data
