services:
  bookmark-manager:
    container_name: bookmark-manager
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: /data/bookmark.db
    ports:
      - "3033:3000"
      - "8044:8000"
    volumes:
      - ./data:/data
